import { Topic } from "@/lib/schema";

export const problems: Record<string, Topic> = {
	Array: {
		name: "Array",
		totalProblems: 32,
		completed: 0,
		problems: [
			{
				id: 1,
				name: "Two Sum",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 4,
				name: "Best Time to Buy and Sell Stock",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 19,
				name: "Majority Element",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 24,
				name: "Contains Duplicate",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 25,
				name: "Meeting Rooms",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 34,
				name: "Move Zeroes",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 41,
				name: "Squares of a Sorted Array",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 43,
				name: "Insert Interval",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 1,
			},
			{
				id: 47,
				name: "3Sum",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 54,
				name: "Product of Array Except Self",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 2,
				name: "Combination Sum",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 4,
				name: "Merge Intervals",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 8,
				name: "Sort Colors",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 18,
				name: "Container With Most Water",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 28,
				name: "Gas Station",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 2,
				name: "Longest Consecutive Sequence",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 3,
				name: "Rotate Array",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 6,
				name: "Contiguous Array",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 17,
				name: "Subarray Sum Equals K",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 3,
			},
			{
				id: 30,
				name: "Meeting Rooms II",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 37,
				name: "3Sum Closest",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 43,
				name: "Non-overlapping Intervals",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 15,
				name: "Employee Free Time",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
			{
				id: 19,
				name: "Sliding Window Maximum",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
		],
	},
	String: {
		name: "String",
		totalProblems: 13,
		completed: 0,
		problems: [
			{
				id: 5,
				name: "Valid Palindrome",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 7,
				name: "Valid Anagram",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 17,
				name: "Longest Palindrome",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 31,
				name: "Longest Common Prefix",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 46,
				name: "Longest Substring Without Repeating Characters",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 11,
				name: "String to Integer (atoi)",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 15,
				name: "Longest Palindromic Substring",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 21,
				name: "Find All Anagrams in a String",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 31,
				name: "Group Anagrams",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 9,
				name: "Longest Repeating Character Replacement",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 28,
				name: "Largest Number",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 34,
				name: "Encode and Decode Strings",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 44,
				name: "Minimum Window Substring",
				difficulty: "Hard",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 20,
				name: "Palindrome Pairs",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	"Binary Tree": {
		name: "Binary Tree",
		totalProblems: 18,
		completed: 0,
		problems: [
			{
				id: 6,
				name: "Invert Binary Tree",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 11,
				name: "Balanced Binary Tree",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 21,
				name: "Diameter of Binary Tree",
				difficulty: "Easy",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 23,
				name: "Maximum Depth of Binary Tree",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 29,
				name: "Same Tree",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 35,
				name: "Symmetric Tree",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 40,
				name: "Subtree of Another Tree",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 48,
				name: "Binary Tree Level Order Traversal",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 5,
				name: "Lowest Common Ancestor of a Binary Tree",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 14,
				name: "Binary Tree Right Side View",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 2,
			},
			{
				id: 17,
				name: "Construct Binary Tree from Preorder and Inorder Traversal",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 1,
				name: "Path Sum II",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 7,
				name: "Maximum Width of Binary Tree",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 23,
				name: "Binary Tree Zigzag Level Order Traversal",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 25,
				name: "Path Sum III",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 3,
			},
			{
				id: 36,
				name: "All Nodes Distance K in Binary Tree",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 1,
				name: "Serialize and Deserialize Binary Tree",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
			{
				id: 9,
				name: "Binary Tree Maximum Path Sum",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
		],
	},
	"Linked List": {
		name: "Linked List",
		totalProblems: 12,
		completed: 0,
		problems: [
			{
				id: 3,
				name: "Merge Two Sorted Lists",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 12,
				name: "Linked List Cycle",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 18,
				name: "Reverse Linked List",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 22,
				name: "Middle of the Linked List",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 33,
				name: "Palindrome Linked List",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 24,
				name: "LRU Cache",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 35,
				name: "Remove Nth Node From End of List",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 2,
			},
			{
				id: 42,
				name: "Swap Nodes in Pairs",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 4,
				name: "Odd Even Linked List",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 12,
				name: "Add Two Numbers",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 14,
				name: "Sort List",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 33,
				name: "Reorder List",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 38,
				name: "Rotate List",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 21,
				name: "Reverse Nodes in k-Group",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
		],
	},
	Stack: {
		name: "Stack",
		totalProblems: 12,
		completed: 0,
		problems: [
			{
				id: 2,
				name: "Valid Parentheses",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 13,
				name: "Implement Queue using Stacks",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 27,
				name: "Backspace String Compare",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 50,
				name: "Evaluate Reverse Polish Notation",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 55,
				name: "Min Stack",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 26,
				name: "Daily Temperatures",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 5,
				name: "Decode String",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 18,
				name: "Asteroid Collision",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 40,
				name: "Basic Calculator II",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 2,
				name: "Trapping Rain Water",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
			{
				id: 5,
				name: "Basic Calculator",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
			{
				id: 8,
				name: "Largest Rectangle in Histogram",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
			{
				id: 10,
				name: "Maximum Frequency Stack",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
			{
				id: 13,
				name: "Longest Valid Parentheses",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
		],
	},
	Graph: {
		name: "Graph",
		totalProblems: 19,
		completed: 0,
		problems: [
			{
				id: 9,
				name: "Flood Fill",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 44,
				name: "01 Matrix",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 49,
				name: "Clone Graph",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 1,
			},
			{
				id: 51,
				name: "Course Schedule",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 57,
				name: "Number of Islands",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 1,
			},
			{
				id: 58,
				name: "Rotting Oranges",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 7,
				name: "Accounts Merge",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 20,
				name: "Word Search",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 22,
				name: "Minimum Height Trees",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 34,
				name: "Pacific Atlantic Water Flow",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 36,
				name: "Shortest Path to Get Food",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 40,
				name: "Graph Valid Tree",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 41,
				name: "Course Schedule II",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 15,
				name: "Number of Connected Components in an Undirected Graph",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 16,
				name: "Minimum Knight Moves",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 3,
			},
			{
				id: 35,
				name: "Cheapest Flights Within K Stops",
				difficulty: "Medium",
				timeLimit: "45 mins",
				week: 3,
			},
			{
				id: 4,
				name: "Word Ladder",
				difficulty: "Hard",
				timeLimit: "45 mins",
				week: 4,
			},
			{
				id: 12,
				name: "Longest Increasing Path in a Matrix",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
			{
				id: 16,
				name: "Word Search II",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
			{
				id: 17,
				name: "Alien Dictionary",
				difficulty: "Hard",
				timeLimit: "45 mins",
				week: 4,
			},
			{
				id: 18,
				name: "Bus Routes",
				difficulty: "Hard",
				timeLimit: "45 mins",
				week: 4,
			},
		],
	},
	"Dynamic Programming": {
		name: "Dynamic Programming",
		totalProblems: 12,
		completed: 0,
		problems: [
			{
				id: 16,
				name: "Climbing Stairs",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 42,
				name: "Maximum Subarray",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 53,
				name: "Coin Change",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 1,
			},
			{
				id: 10,
				name: "Partition Equal Subset Sum",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 16,
				name: "Unique Paths",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 2,
			},
			{
				id: 27,
				name: "House Robber",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 32,
				name: "Maximum Product Subarray",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 39,
				name: "Longest Increasing Subsequence",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 11,
				name: "Jump Game",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 21,
				name: "Maximal Square",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 29,
				name: "Decode Ways",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 41,
				name: "Combination Sum IV",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 3,
			},
		],
	},
	"Binary Search": {
		name: "Binary Search",
		totalProblems: 8,
		completed: 0,
		problems: [
			{
				id: 8,
				name: "Binary Search",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 14,
				name: "First Bad Version",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 1,
				name: "Search in Rotated Sorted Array",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 6,
				name: "Time Based Key-Value Store",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 27,
				name: "Search a 2D Matrix",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 39,
				name: "Find Minimum in Rotated Sorted Array",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 6,
				name: "Maximum Profit in Job Scheduling",
				difficulty: "Hard",
				timeLimit: "45 mins",
				week: 4,
			},
			{
				id: 11,
				name: "Median of Two Sorted Arrays",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	"Binary Search Tree": {
		name: "Binary Search Tree",
		totalProblems: 4,
		completed: 0,
		problems: [
			{
				id: 10,
				name: "Lowest Common Ancestor of a Binary Search Tree",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 38,
				name: "Convert Sorted Array to Binary Search Tree",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 56,
				name: "Validate Binary Search Tree",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 25,
				name: "Kth Smallest Element in a BST",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 10,
				name: "Inorder Successor in BST",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
		],
	},
	Binary: {
		name: "Binary",
		totalProblems: 7,
		completed: 0,
		problems: [
			{
				id: 20,
				name: "Add Binary",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 28,
				name: "Counting Bits",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 30,
				name: "Number of 1 Bits",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 32,
				name: "Single Number",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 36,
				name: "Missing Number",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 39,
				name: "Reverse Bits",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 37,
				name: "Find the Duplicate Number",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 2,
			},
		],
	},
	Heap: {
		name: "Heap",
		totalProblems: 7,
		completed: 0,
		problems: [
			{
				id: 45,
				name: "K Closest Points to Origin",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 1,
			},
			{
				id: 23,
				name: "Task Scheduler",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 38,
				name: "Top K Frequent Words",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 8,
				name: "Find K Closest Elements",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 20,
				name: "Kth Largest Element in an Array",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
			{
				id: 3,
				name: "Find Median from Data Stream",
				difficulty: "Hard",
				timeLimit: "30 mins",
				week: 4,
			},
			{
				id: 7,
				name: "Merge k Sorted Lists",
				difficulty: "Hard",
				timeLimit: "30 mins",
				week: 4,
			},
			{
				id: 25,
				name: "Smallest Range Covering Elements from K Lists",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	"Hash Table": {
		name: "Hash Table",
		totalProblems: 3,
		completed: 0,
		problems: [
			{
				id: 15,
				name: "Ransom Note",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 42,
				name: "Insert Delete GetRandom O(1)",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 23,
				name: "First Missing Positive",
				difficulty: "Hard",
				timeLimit: "35 mins",
				week: 4,
			},
		],
	},
	Trie: {
		name: "Trie",
		totalProblems: 4,
		completed: 0,
		problems: [
			{
				id: 52,
				name: "Implement Trie (Prefix Tree)",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 1,
			},
			{
				id: 9,
				name: "Word Break",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 33,
				name: "Design Add and Search Words Data Structure",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 14,
				name: "Design In-Memory File System",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	Math: {
		name: "Math",
		totalProblems: 5,
		completed: 0,
		problems: [
			{
				id: 26,
				name: "Roman to Integer",
				difficulty: "Easy",
				timeLimit: "20 mins",
				week: 1,
			},
			{
				id: 37,
				name: "Palindrome Number",
				difficulty: "Easy",
				timeLimit: "15 mins",
				week: 1,
			},
			{
				id: 19,
				name: "Random Pick with Weight",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 26,
				name: "Pow(x, n)",
				difficulty: "Medium",
				timeLimit: "20 mins",
				week: 3,
			},
			{
				id: 31,
				name: "Reverse Integer",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
		],
	},
	Matrix: {
		name: "Matrix",
		totalProblems: 4,
		completed: 0,
		problems: [
			{
				id: 12,
				name: "Spiral Matrix",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 2,
			},
			{
				id: 30,
				name: "Valid Sudoku",
				difficulty: "Medium",
				timeLimit: "35 mins",
				week: 2,
			},
			{
				id: 22,
				name: "Rotate Image",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 32,
				name: "Set Matrix Zeroes",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 22,
				name: "Sudoku Solver",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	Recursion: {
		name: "Recursion",
		totalProblems: 6,
		completed: 0,
		problems: [
			{
				id: 3,
				name: "Permutations",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 13,
				name: "Subsets",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 19,
				name: "Letter Combinations of a Phone Number",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 29,
				name: "Next Permutation",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 2,
			},
			{
				id: 13,
				name: "Generate Parentheses",
				difficulty: "Medium",
				timeLimit: "25 mins",
				week: 3,
			},
			{
				id: 24,
				name: "N-Queens",
				difficulty: "Hard",
				timeLimit: "40 mins",
				week: 4,
			},
		],
	},
	Queue: {
		name: "Queue",
		totalProblems: 1,
		completed: 0,
		problems: [
			{
				id: 24,
				name: "Design Hit Counter",
				difficulty: "Medium",
				timeLimit: "30 mins",
				week: 3,
			},
		],
	},
};
